### ISSUE TITLE
RubyのDockerイメージのバージョンアップ

### ISSUE THREAD

**Issue by tyanakaz** [tyanakaz/atNuda-api#14]
Ruby 2.5.4がリリース
https://www.ruby-lang.org/ja/news/2019/03/13/ruby-2-5-4-released/

Dockerイメージの更新はまだなので、ここに追加されたら、イメージを最新バージョンに変更
https://hub.docker.com/_/ruby

**Comment by tyanakaz** [comment]
結構危険な修正が入ったので、リリースまでには必ずバージョンアップした方が良さそう

https://www.ruby-lang.org/ja/news/2019/03/15/ruby-2-5-5-released/

**Comment by 3isawa** [comment]
バージョンアップありがとうございます！
問題無いようでしたらCloseをお願いいたします。

**Comment by tyanakaz** [comment]
バージョンアップは完了してますのでクローズしますー
