### ISSUE TITLE
dependent設定が逆になっている

### ISSUE THREAD

**Issue by tyanakaz** [tyanakaz/atNuda-api#15]
申し訳ございません、私が残していた間違いに引っ張られてしまったのだと思いますが、以下の修正が必要です。

`dependent: :destroy`がcorrectionモデルに設定されていますが、これだとcorrection削除時にuserを削除する設定になっています。

https://github.com/tyanakaz/atNuda-api/blob/9b00912a21d97454944abcd8e2c13c51794946d8/app/models/correction.rb#L3-L6

実際は、こちらに記載するのが正しいです。

https://github.com/tyanakaz/atNuda-api/blob/9b00912a21d97454944abcd8e2c13c51794946d8/app/models/portfolio.rb#L3-L4

**Comment by tyanakaz** [comment]
あ、has_manyが抜けてますね。。レビューで見落としていたようです。

**Comment by 3isawa** [comment]
こちら解消しました。
よろしければCloseをお願いいたします。

**Comment by tyanakaz** [comment]
これも終了してますのでクローズですー
